networks:
  localnetwork:
    driver: bridge
    attachable: true
services:
  web:
    build:
      context: ./
      dockerfile: Docker/web.Dockerfile
  api:
    build:
      context: ./
      dockerfile: Docker/api.Dockerfile
