networks:
  localnetwork:
    name: openpassvault_local
services:
  web:
    container_name: web
    restart: always
    ports:
      - "5000:80"
    depends_on:
      - api
    networks:
      - localnetwork
  api:
    container_name: api
    restart: always
    env_file: Docker/api.env
    ports:
      - "5001:8080"
    depends_on:
      - db
    networks:
      - localnetwork
  db:
    container_name: db
    image: mysql:8.4.0
    command: --mysql-native-password=ON
    restart: always
    env_file: Docker/db.env
    ports:
      - "3306:3306"
    volumes:
      - ./Docker/db/data:/var/lib/mysql
    networks:
      - localnetwork
